tasks:

  - source: tasks/process_data.py
    product:
      nb: '{{folder_output}}/notebooks/process_data.ipynb'
      processed_data: '{{folder_output}}/processed_data/'
    params:
      folder_input: '{{folder_input}}'

  - source: tasks/clean_missing_values.py
    product:
      nb: '{{folder_output}}/notebooks/clean_missing_values.ipynb'
      cleaned_csv: '{{folder_output}}/cleaned_csv/'

  - source: tasks/insert_ids.py
    product:
      nb: '{{folder_output}}/notebooks/insert_ids.ipynb'
      inserted_ids: '{{folder_output}}/inserted_ids/'

  - source: tasks/calc_dist_matrix.py
    product:
      nb: '{{folder_output}}/notebooks/calc_dist_matrix.ipynb'
      calculated_dist_matrix: '{{folder_output}}/calculated_dist_matrix/'
    params:
      dist_matrix_type: '{{dist_matrix_type}}'
      target_column: "{{target_column}}"

  - source: tasks/generate_histogram.py
    product:
      nb: '{{folder_output}}/notebooks/generate_histogram.ipynb'
      generated_histograms: '{{folder_output}}/generated_histograms/'
    params:
      target_column: "{{target_column}}"

  - source: tasks/generate_scatterplot.py
    product:
      nb: '{{folder_output}}/notebooks/generate_scatterplot.ipynb'
      generated_scatterplot: '{{folder_output}}/generated_scatterplot/'
    params:
      list_column: "{{list_column}}"

  - source: tasks/generate_clusters.py
    product:
      nb: '{{folder_output}}/notebooks/generate_clusters.ipynb'
      generated_clusters: '{{folder_output}}/generated_clusters/'
    params:
      dist_matrix_type: '{{dist_matrix_type}}'
      clusters: '{{clusters}}'
      clust_method: '{{clust_method}}'
      list_column: "{{list_column}}"

  - source: tasks/generate_PCA.py
    product:
      nb: '{{folder_output}}/notebooks/generate_PCA.ipynb'
      generated_PCA: '{{folder_output}}/generated_PCA/'
    params:
      list_column: "{{list_column}}"