tasks:

  - source: tasks/convert_xlsx_to_csv.py
    product:
      nb: '{{folder_output}}/notebooks/convert_xlsx_to_csv.ipynb'
      converted_xlsx_to_csv: '{{folder_output}}/converted_xlsx_to_csv/'
    params:
      folder_input: '{{folder_input}}'

  - source: tasks/clean_missing_values.py
    product:
      nb: '{{folder_output}}/notebooks/clean_missing_values.ipynb'
      cleaned_csv: '{{folder_output}}/cleaned_csv/'

  - source: tasks/calc_dist_matrix.py
    product:
      nb: '{{folder_output}}/notebooks/calc_dist_matrix.ipynb'
      calculated_dist_matrix: '{{folder_output}}/calculated_dist_matrix/'
    params:
      dist_matrix_type: '{{dist_matrix_type}}'
      value: "{{value}}"
      name: "{{name}}"
  
  - source: tasks/generate_clusters.py
    product:
      nb: '{{folder_output}}/notebooks/generate_clusters.ipynb'
      generated_clusters: '{{folder_output}}/generated_clusters/'
    params:
      dist_matrix_type: '{{dist_matrix_type}}'
      clusters: '{{clusters}}'
      method: '{{method}}'
      value: "{{value}}"
      name: "{{name}}"